---
title: "'Throw' 陳述式不可以在 'Catch' 陳述式外或 'Finally' 陳述式內省略運算元"
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 17e7817c608e9c3513e0320b62f42410613f33b0
ms.sourcegitcommit: 558d78d2a68acd4c95ef23231c8b4e4c7bac3902
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 04/09/2019
ms.locfileid: "59302487"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a>'Throw' 陳述式不可以在 'Catch' 陳述式外或 'Finally' 陳述式內省略運算元
`Throw` 陳述式外的 `Catch` 陳述式必須提供例外狀況物件的名稱。  
  
 **錯誤 ID:** BC30666  
  
## <a name="to-correct-this-error"></a>更正這個錯誤  
  
1. 指定衍生自 `System.Exception`之例外狀況物件的名稱。  
  
2. 重建您的程式碼，讓 `Throw` 陳述式位於 `Catch` 區塊內。  
  
## <a name="see-also"></a>另請參閱

- [Throw 陳述式](../../visual-basic/language-reference/statements/throw-statement.md)
- [Try...Catch...Finally 陳述式](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [在 .NET 中處理和擲回例外狀況](../../standard/exceptions/index.md)
